// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genesis.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Peer struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Endpoint             string   `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	PublicKey            string   `protobuf:"bytes,4,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,5,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_14205810582f3203, []int{0}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Peer) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Peer) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Peer) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Peer) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type GetTargetRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTargetRequest) Reset()         { *m = GetTargetRequest{} }
func (m *GetTargetRequest) String() string { return proto.CompactTextString(m) }
func (*GetTargetRequest) ProtoMessage()    {}
func (*GetTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14205810582f3203, []int{1}
}

func (m *GetTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTargetRequest.Unmarshal(m, b)
}
func (m *GetTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTargetRequest.Marshal(b, m, deterministic)
}
func (m *GetTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTargetRequest.Merge(m, src)
}
func (m *GetTargetRequest) XXX_Size() int {
	return xxx_messageInfo_GetTargetRequest.Size(m)
}
func (m *GetTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTargetRequest proto.InternalMessageInfo

func (m *GetTargetRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetTargetResponse struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTargetResponse) Reset()         { *m = GetTargetResponse{} }
func (m *GetTargetResponse) String() string { return proto.CompactTextString(m) }
func (*GetTargetResponse) ProtoMessage()    {}
func (*GetTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14205810582f3203, []int{2}
}

func (m *GetTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTargetResponse.Unmarshal(m, b)
}
func (m *GetTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTargetResponse.Marshal(b, m, deterministic)
}
func (m *GetTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTargetResponse.Merge(m, src)
}
func (m *GetTargetResponse) XXX_Size() int {
	return xxx_messageInfo_GetTargetResponse.Size(m)
}
func (m *GetTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTargetResponse proto.InternalMessageInfo

func (m *GetTargetResponse) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *GetTargetResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisterRequest struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14205810582f3203, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisterResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14205810582f3203, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GenesisRequest struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	TargetPeer           string   `protobuf:"bytes,2,opt,name=targetPeer,proto3" json:"targetPeer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisRequest) Reset()         { *m = GenesisRequest{} }
func (m *GenesisRequest) String() string { return proto.CompactTextString(m) }
func (*GenesisRequest) ProtoMessage()    {}
func (*GenesisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14205810582f3203, []int{5}
}

func (m *GenesisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisRequest.Unmarshal(m, b)
}
func (m *GenesisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisRequest.Marshal(b, m, deterministic)
}
func (m *GenesisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisRequest.Merge(m, src)
}
func (m *GenesisRequest) XXX_Size() int {
	return xxx_messageInfo_GenesisRequest.Size(m)
}
func (m *GenesisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisRequest proto.InternalMessageInfo

func (m *GenesisRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *GenesisRequest) GetTargetPeer() string {
	if m != nil {
		return m.TargetPeer
	}
	return ""
}

func init() {
	proto.RegisterType((*Peer)(nil), "proto.Peer")
	proto.RegisterType((*GetTargetRequest)(nil), "proto.GetTargetRequest")
	proto.RegisterType((*GetTargetResponse)(nil), "proto.GetTargetResponse")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*GenesisRequest)(nil), "proto.GenesisRequest")
}

func init() {
	proto.RegisterFile("genesis.proto", fileDescriptor_14205810582f3203)
}

var fileDescriptor_14205810582f3203 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xcd, 0x5c, 0xb7, 0xf5, 0x82, 0x73, 0xe6, 0x61, 0x86, 0x22, 0x22, 0x79, 0xf2, 0xa9,
	0x0f, 0xfa, 0x2c, 0xf8, 0xb0, 0x31, 0xc7, 0x10, 0x4a, 0xd5, 0x1f, 0xd0, 0xb9, 0x4b, 0x29, 0x68,
	0x5b, 0x93, 0x54, 0xf0, 0x2f, 0x88, 0x3f, 0xda, 0x36, 0x4d, 0xb6, 0xb6, 0x83, 0xed, 0xa9, 0x3d,
	0xe7, 0x84, 0xaf, 0x27, 0xf7, 0x16, 0xce, 0x62, 0x4c, 0x51, 0x26, 0xd2, 0xcf, 0x45, 0xa6, 0x32,
	0xea, 0xe8, 0x07, 0xff, 0x23, 0xd0, 0x0f, 0x10, 0x05, 0x1d, 0x43, 0x6f, 0x39, 0x63, 0xe4, 0x86,
	0xdc, 0xba, 0x61, 0xf9, 0x46, 0x3d, 0x18, 0xbd, 0x49, 0x14, 0x69, 0xf4, 0x89, 0xac, 0xa7, 0xdd,
	0xad, 0xae, 0xb2, 0x79, 0xba, 0xc9, 0xb3, 0x24, 0x55, 0xec, 0xb4, 0xce, 0xac, 0xa6, 0x57, 0xe0,
	0x06, 0xc5, 0xfa, 0x23, 0x79, 0x5f, 0xe1, 0x0f, 0xeb, 0xeb, 0x70, 0x67, 0xd0, 0x6b, 0x80, 0x40,
	0x24, 0xdf, 0x91, 0xc2, 0x2a, 0x76, 0x74, 0xdc, 0x70, 0xb8, 0x0f, 0x93, 0x05, 0xaa, 0xd7, 0x48,
	0xc4, 0xa8, 0x42, 0xfc, 0x2a, 0x50, 0xaa, 0x56, 0x13, 0xd2, 0x6e, 0xc2, 0x57, 0x70, 0xd1, 0x38,
	0x2f, 0xf3, 0x2c, 0x95, 0xed, 0x7a, 0xa4, 0x53, 0xef, 0xc0, 0xb5, 0xf8, 0x1c, 0xce, 0x43, 0x8c,
	0x13, 0xa9, 0x50, 0xd8, 0x6f, 0x4f, 0x61, 0x90, 0x97, 0xd3, 0x59, 0x6e, 0x0c, 0xc8, 0xa8, 0x83,
	0x98, 0x19, 0x4c, 0x76, 0x18, 0x53, 0xa9, 0xe4, 0xbc, 0xa8, 0x48, 0x15, 0x52, 0x73, 0x9c, 0xd0,
	0x28, 0xca, 0x60, 0xf8, 0x8c, 0x52, 0x46, 0xb1, 0xc5, 0x58, 0xc9, 0x9f, 0x60, 0xbc, 0xa8, 0x17,
	0x76, 0xac, 0x4b, 0x39, 0x53, 0xa5, 0x07, 0x50, 0xed, 0xd1, 0x60, 0x1a, 0xce, 0xdd, 0x2f, 0x81,
	0xa1, 0x41, 0xd1, 0x07, 0x18, 0xd9, 0x6e, 0x74, 0x5a, 0xff, 0x09, 0x7e, 0xe7, 0xce, 0xde, 0xe5,
	0x9e, 0x5f, 0x5f, 0x82, 0x9f, 0xd0, 0x47, 0x70, 0xb7, 0xe3, 0xa6, 0xf6, 0x5c, 0x77, 0x61, 0x1e,
	0xdb, 0x0f, 0x2c, 0x61, 0x3d, 0xd0, 0xd1, 0xfd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x90,
	0x10, 0x87, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GenesisClient is the client API for Genesis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenesisClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*GetTargetResponse, error)
}

type genesisClient struct {
	cc grpc.ClientConnInterface
}

func NewGenesisClient(cc grpc.ClientConnInterface) GenesisClient {
	return &genesisClient{cc}
}

func (c *genesisClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.Genesis/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genesisClient) GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*GetTargetResponse, error) {
	out := new(GetTargetResponse)
	err := c.cc.Invoke(ctx, "/proto.Genesis/GetTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenesisServer is the server API for Genesis service.
type GenesisServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetTarget(context.Context, *GetTargetRequest) (*GetTargetResponse, error)
}

// UnimplementedGenesisServer can be embedded to have forward compatible implementations.
type UnimplementedGenesisServer struct {
}

func (*UnimplementedGenesisServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedGenesisServer) GetTarget(ctx context.Context, req *GetTargetRequest) (*GetTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTarget not implemented")
}

func RegisterGenesisServer(s *grpc.Server, srv GenesisServer) {
	s.RegisterService(&_Genesis_serviceDesc, srv)
}

func _Genesis_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenesisServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Genesis/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenesisServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Genesis_GetTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenesisServer).GetTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Genesis/GetTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenesisServer).GetTarget(ctx, req.(*GetTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Genesis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Genesis",
	HandlerType: (*GenesisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Genesis_Register_Handler,
		},
		{
			MethodName: "GetTarget",
			Handler:    _Genesis_GetTarget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genesis.proto",
}
